set(header "channel,value,warning_min,warning_max,critical_min,critical_max,unit,age_seconds,warning_age_seconds,max_age_seconds\n")
set(first "Pressure,100,90,110,80,120,kPa,1,3,5\n")
set(duplicate "Pressure,99,90,110,80,120,kPa,1,3,5\n")
set(path "${CMAKE_CURRENT_BINARY_DIR}/channel_identity.csv")

foreach(mode human json prometheus)
    if(mode STREQUAL "human")
        set(option "")
    else()
        set(option "--${mode}")
    endif()
    foreach(case duplicate blank padded)
        if(case STREQUAL "duplicate")
            set(second "${duplicate}")
            set(expected "CSV line 3: duplicate channel: Pressure")
        elseif(case STREQUAL "blank")
            set(second "   ,99,90,110,80,120,kPa,1,3,5\n")
            set(expected "CSV line 3: channel name cannot be blank")
        else()
            set(second " Pressure,99,90,110,80,120,kPa,1,3,5\n")
            set(expected "CSV line 3: channel name has surrounding whitespace")
        endif()
        file(WRITE "${path}" "${header}${first}${second}")
        execute_process(COMMAND "${TELEMETRY_GUARD}" --csv "${path}" ${option}
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error_output)
        if(NOT result EQUAL 3 OR NOT output STREQUAL "" OR NOT error_output MATCHES "${expected}")
            message(FATAL_ERROR "${mode} ${case} was not rejected: ${result}\n${output}\n${error_output}")
        endif()
    endforeach()
endforeach()
file(REMOVE "${path}")
